apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-service.fullname" . }}
  labels:
    {{- include "gateway-service.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  SPRING_DATA_REDIS_HOST: {{ .Values.config.redisHost | quote }}
  SPRING_DATA_REDIS_PORT: {{ .Values.config.redisPort | quote }}
  ZIPKIN_ENDPOINT: {{ .Values.config.zipkinEndpoint | quote }}
  TRACING_SAMPLING_PROBABILITY: {{ .Values.config.tracingSamplingProbability | quote }}
