apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shipment-service.fullname" . }}
  labels:
    {{- include "shipment-service.labels" . | nindent 4 }}
type: Opaque
data:
  SHIPMENT_DB_USERNAME: {{ .Values.secret.dbUsername | b64enc | quote }}
  SHIPMENT_DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
