apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-service.fullname" . }}
  labels:
    {{- include "inventory-service.labels" . | nindent 4 }}
type: Opaque
data:
  INVENTORY_DB_USERNAME: {{ .Values.secret.dbUsername | b64enc | quote }}
  INVENTORY_DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
