replicaCount: 2

image:
  pullPolicy: Always

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

config:
  redisHost: "redis-master.production.svc.cluster.local"
  redisPort: "6379"
  zipkinEndpoint: "http://zipkin.production.svc.cluster.local:9411/api/v2/spans"
  tracingSamplingProbability: "0.1"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
