apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-service.fullname" . }}
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
type: Opaque
data:
  ORDER_DB_USERNAME: {{ .Values.secret.dbUsername | b64enc | quote }}
  ORDER_DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
  JWT_SECRET: {{ required "secret.jwtSecret must be set at install time" .Values.secret.jwtSecret | b64enc | quote }}
